### PR TITLE
Feat: Re-written in typescript

### PR DESCRIPTION
**Pull request by irohitb**

### CODE REVIEW

**Comment by niftylettuce** [comment]
Thanks, just releasing now to npm as v3.0.0.  Would you be interested in becoming a maintainer?

**Comment by niftylettuce** [comment]
Released https://github.com/joinspontaneous/react-native-loading-spinner-overlay/releases/tag/v3.0.0

**Comment by irohitb** [comment]
@niftylettuce Definitely :)

**Comment by cristianoccazinsp** [comment]
What needs to be changed for this update to work? I've simply upgraded but the component as it was before no longer shows.

**Pull request merged**
