### PR TITLE
Issue #27 - add support for custom spinner gif

### PR DESCRIPTION
**Pull request by b8ne**
Hey @niftylettuce  ive implemented this.  All works fine, the only issue I had was the spinner 'key'.  Because it referenced date.now() the gif kept flashing.  I changed it to a constant which fixed it, and the native indicator still works.  Its a little bit beyond my current knowledge so let me know if there was a reason for this and ill fix it.
Cheers

### CODE REVIEW

**Comment by niftylettuce** [comment]
whats the status on this?  does this PR need updated?

**Comment by b8ne** [comment]
Hey mate it builds and works fine. So if you're happy with it then merge it.  Just mentioned that incase i missed the reasoning behind that key.

**Comment by SandroMachado** [comment]
I think this was deprecated by #37. This can be closed. @niftylettuce WDYT?

**Comment by niftylettuce** [comment]
Correct, you can add a custom spinner now via:

```js
<Spinner visible={this.state.visible}>
  <Text>This is my custom spinner</Text>
</Spinner>
```

**Pull request closed without merging**
